### ISSUE TITLE
Docker Alpine ex_secp256k1 NIF won't load when application starts up

### ISSUE THREAD

**Issue by willjleong** [omgnetwork/ex_secp256k1#6]
Not sure if anyone ran into this, but when trying to run my elixir phoenix app for deployment in an alpine docker container with ex_secp256k1 as a dependency, I'm able to fully build the elixir app after installing rust and cargo in the docker container with no errors but then get an error related to `on_load_function_failed` for ex_secp256k1 when the application start ups.

```
#{label=>{application_controller,exit},report=>[{application,kernel},{exited,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.ExSecp256k1'}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
```

I'm trying to figure out how to debug it better because this error is too vague especially because my app & deps all build with no issues.

erlang 23.3.4.4
elixir 1.11.4-otp-23
nodejs 14.17.0
rust 1.22.0

**Comment by feld** [comment]
I'm seeing this as well.

**Comment by feld** [comment]
Install `libgcc` in the alpine image and the issue goes away.

```
Error loading shared library libgcc_s.so.1: No such file or directory (needed by libexsecp256k1.so)
```

**Comment by willjleong** [comment]
Thanks @feld , I was able to solve by adding libgcc and now working backwards from a single stage Dockerfile
